# Generated by Django 6.0.3 on 2026-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('event', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('notable_person', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
