# Generated by Django 6.0.3 on 2026-03-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_historicalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqltask',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
